services:
  cdn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdn
    ports:
      - "8080:8080"
    volumes:
      - "./cdn/cdn:/app/cdn"
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"
    restart: unless-stopped